#!/usr/bin/env python3

import time
import colors as c
print(c.clear)

snake = '''
 (                             
 )\ )                 )        
(()/(           )  ( /(    (   
 /(_)) (     ( /(  )\())  ))\  
(_))   )\ )  )(_))((_)\  /((_) 
/ __| _(_/( ((_)_ | |(_)(_))   
\__ \| ' \))/ _` || / / / -_)  
|___/|_||_| \__,_||_\_\ \___|  
                               
'''

for count in range(5):

    for badger in range (12):
        print(c.blue + " Badgers!")
        time.sleep(0.4)

    for mushroom in range (2):
        print(c.red + "Muuussshrooom")
        time.sleep(0.8)   
print(c.clear)
print(c.yellow + snake)

