#!/usr/bin/env python3

import colors as c

print(c.blue + 'Do you like Waffles!')

waffles + input(c.red + "> ")


if waffles == "yes":
  print('Yes!!!')
  
print(c.yellow + 'Do you like Pancakes?')




