#!/usr/bin/env python3

import colors as c

while True:
    sides = [1,2,3,4,5,6]
    print(c.clear)
    print(c.blue + '1')
    print(c.yellow + '2')
    print(c.magenta + '3')
    print(c.red + '4')
    print(c.blue  + '5')
    print(c.red  + '6')


