#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.yellow + 'do you like waffles')
waffles = input(' >')
if waffles == 'yes':
    print('YAY!!!!')
else:
   print('oh...')

print(c.red + 'do you like pancakes')
pancakes = input(' >')
if pancakes == 'yes':
    print(':D')
else:
   print(':P')

print(c.blue + 'do you like french toast')
frenchtoast = input(' >')
if frenchtoast == 'yes':
        print(':D :D :D')
else:
   print(':(')
