#!/usr/bin/env python3
print(c.clear)
print('Do you like waffles?')
answer = input('> ')
if answer == 'yes':
    print(c.yellow + 'Yas!!!!')

if answer == 'no':
    print(c.red + ' How Dare You!!!')



